sudo: required
language: generic 
services:
    - docker

before_install:
    - docker build -t sandergit180/docker-test -f Dockerfile.dev .

script:
    - docker run -e CI=true sandergit180/docker-test npm run test